#! /bin/bash
set -eu

DATE=$(date +"%y%m%d")
FILES="komob.hpp README.md"

for FILE in $FILES; do
  awk -v d="$DATE" '
    {
      if ($0 ~ /^\/\/[[:space:]]*Version:/) {
        print "// Version: " d " //"
      } else {
        print
      }
    }
  ' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
  git add "$FILE"
done
